name: movies ci
on:
    push:
        branches:
            - main
env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
    build_and_push:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo
              uses: actions/checkout@v2

            - name: setup docker
              uses: docker/setup-buildx-action@v1

            - name: login to docker hub
              uses: docker/login-action@v1
              with:
                username: ${{ env.DOCKER_USERNAME }}
                password: ${{ env.DOCKER_PASSWORD }}

            - name: build an push
              uses: docker/build-push-actions@v2
              with:
                context: .
                push: true
                tags: ${{env.DOCKER_USERNAME}}/movies:latest